name: Run Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: 3.12
    
    - name: Set up Conda
      uses: conda-incubator/setup-miniconda@v3
      with:
        auto-update-conda: true
        python-version: 3.12
        environment-file: conda-env.yml
        activate-environment: TREC-eml-translator
    
    - name: Install dependencies
      shell: bash -l {0}
      run: |
        conda activate TREC-eml-translator
        pip install -r requirements.txt
    
    - name: Run unit tests
      shell: bash -l {0}
      run: |
        conda activate TREC-eml-translator
        python -m unittest discover -s tests -p "test_*.py" -v
